# General
seed: 42
exp_name: "LQ_base"
exp_vars: null
save_episode: True
save_model: True

# Environment
task: LQ-reftrack
discount: 1
episode_length: 10
dist_std: 1e-2
noise_std: 0.

# General policy
policy_type: "CVXPY"
horizon: 5
action_std: 1e-2
init: null
n_params: 20
# CVXPY policy
u_lim: null

# General learning
algo: 'REINFORCE'
num_epi_batches: 101
epi_batch_size: 64
# BO
acq_fun: 'UCB'
bo_beta: 0.1
# PGT
lr: 1e-1
grad_clip_norm: 10
# Q-network
mlp_dim: 64 # 512
